name: dart_colorful_cmd
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
dependencies: 
  ansicolor: ^2.0.1
  dio: ^4.0.0
  encrypt: ^5.0.0
  enough_ascii_art: ^1.0.0
